### ISSUE TITLE
Unable to enable Probeam after installing

### ISSUE THREAD

**Issue by hydino2085143** [Adobe12327/Probeam#1]
Blender version: 3.1.2
Probeam version: 1.0.0

Upon installing Probeam, when I try to enable the add-on, it errors out:
![image](https://user-images.githubusercontent.com/46134462/172129183-1d690e9b-01c3-4ac5-aa18-b9518c2bb1ce.png)

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addons_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'Probeam-1'
```

**Comment by Derpitron** [comment]
The only file within the Probeam 1.0.0 release .zip is the `__init__.py`, and `UI` and `yaml` folders.

Upon downloading and trying the zip file of the latest commit d949e1e936b3073f9723dc5c26fd2f2ca0e912a2, there is no error, so your releases are missing the necessary files.
